### ISSUE TITLE
create proper dir structure

### ISSUE THREAD

**Issue by stfl** [hobler/miniTopSim#1]
Ordner Struktur

/code/...py
/work/AufgabeXY/...py

**Comment by rafaaar** [comment]
Jetzt sollte Ordnerstruktur passen. Hab den Simulator, wie besprochen, die Paramter aus der parameters.db Datei übergeben.

**Comment by stfl** [comment]
es geht darum, dass die ordnerstruktur immer noch nicht passt...
es gibt jetzt einen /miniTopSim/ ordner, der nicht dort sein sollte..
code/ und work/ sollen herausgezogen werden!

und bitte UNBEDINGT __pycache__ loeschen!
das sollte eigentlich durch die .gitignore verhindert werden.. wie hast du das geschafft, das zu adden?

**Comment by rafaaar** [comment]
Ok,  ja stimmt hab den ganzen Überordner "miniTopSim" hinzugefügt anstatt nur die Unterordenr "work" und "code". Hab den Ordner __pycache__ jetzt gelöscht. Wusste nicht das man das tun muss hab davor ebm noch nie was mit GitHub gemacht. Hoffe es passt jetzt.

**Comment by stfl** [comment]
der pycache ordner is halt so ein artefakt, dass beim ausfuehren entsteht.. das braucht man in nem repo nicht..
bitte jetzt noch den miniTopSim ordner loeschen ;D

**Comment by stfl** [comment]
done..

**Comment by rafaaar** [comment]
danke =)
