### ISSUE TITLE
Code is not runnable

### ISSUE THREAD

**Issue by salykovaa** [hobler/miniTopSim#2]
Hi @danielSchTu

I tried to run minitopsim/main.py, but got error 
```from . import parameters as par```
```ImportError: attempted relative import with no known parent package ```

Have I done something wrong, or the code is broken? The same problem with all other files containing relative imports.

**Comment by danielSchTu** [comment]
As per instruction I used relative imports ( page 7 "Hinweis: ...." ) you can execute the code by using the run.py script in templates.

I hope that helps.

**Comment by danielSchTu** [comment]
Appendum you can also execute it, by telling python that you want to use the main file as part of a module:
python -m minitopsim.main <cfg file>

**Comment by salykovaa** [comment]
Aahh ok, I get it, thanks!
